### PR TITLE
fix(addon-table): don't update direction order when updating sorter programmatically

### LINKED ISSUE #2969: 🐞 - disable automatic trigger for `sort$` and `direction$`
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/table

### Is this issue blocking you?

Non-Blocking

### Description

I store table settings in url - sortOrder, sortBy, page, size. When parameters change (for example, when navigating back), I update the table settings.

Moreover, if I simultaneously call both sort$ and direction$ (which are passed to the direction and tuiSortBy inputs), then the table itself will trigger the change of direction$ to asc (1) when sort$ changes. This is inconvenient, because sometimes I need to restore the direction desc.

I would generally expect that if I manage the settings programmatically, then this automatic change of direction to asc will not happen.

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2969 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/addon-table/components/table/directives/table.directive.ts [hunk 1]
```diff
@@ -63,21 +63,30 @@ export class TuiTableDirective<
...
-
-        this.change$.next();
     }
 
     ngAfterViewInit(): void {
         this.changeDetectorRef.detectChanges();
     }
+
+    updateSorter(sorter: TuiComparator<T> | null): void {
+        if (sorter !== this.sorter) {
```
Comment (nsbarsukov) [inline projects/addon-table/components/table/directives/table.directive.ts:80]: If I've not mistaken, this condition is checked twice (some lines above and here).

Do we really need this double check ?

**Review by nsbarsukov — APPROVED** [review]

File: projects/addon-table/components/table/directives/table.directive.ts (hunk 1 above)
Comment (vladimirpotekhin) [reply projects/addon-table/components/table/directives/table.directive.ts]: oh this function also called independently, from `Sortable` [directive](https://github.com/Tinkoff/taiga-ui/blob/335455cd644d15dad156e6fbe51e3d7246257325/projects/addon-table/components/table/directives/sortable.directive.ts#L36)
But you are right, `Sortable` has the same check, so I removed 👍
