### PR TITLE
fix(kit): `InputSlider` fix decimal limit

### LINKED ISSUE #1212: 🐞 - `InputSlider` mask cuts more than 2 decimals
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

_No response_

### Description

It is currently not possible to enter a value with 3 or more decimals cause the default decimalLimit in the mask is 2

### Angular version

9>

### Taiga UI version

2.30

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1212 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/kit/abstract/input-slider.ts [hunk 1]
```diff
@@ -143,6 +144,10 @@ export abstract class AbstractTuiInputSlider<T>
         this.updateHovered(hovered);
     }
 
+    private get decimalLimit(): number {
```
Comment (splincode) [inline projects/kit/abstract/input-slider.ts:147]:
```ts
private get decimalLimit(): number {
   const [, fractionPart = ''] = this.quantum.toString().split('.');
   return fractionPart.length || 2;
}
```

`2` - Do we need to move/provide this value to a constant?

**Review by splincode — APPROVED** [review]

File: projects/kit/abstract/input-slider.ts (hunk 1 above)
Comment (vladimirpotekhin) [reply projects/kit/abstract/input-slider.ts:147]: @splincode  thanks, done 👍  

@waterplea  getter is only called from TuiMapper depending on quantum. So I think another tuiPure would be redundant. What do you think?

Comment (waterplea) [reply projects/kit/abstract/input-slider.ts:147]: Right, it's already memoized. Let's change it to a function instead of getter, that gets `quantum` as an argument to keep mapping function pure.

**Review by waterplea — APPROVED** [review]
