### PR TITLE
fix: hosts of portals can throw `ExpressionChangedAfterItHasBeenCheckedError`

### LINKED ISSUE #4473: 🐞 - ExpressionChangedAfterItHasBeenCheckedError when hiding a button with hint active
### Playground Link

https://stackblitz.com/edit/angular-llisre?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts&hideExplorer=1

### Description

Firstly, please note that the issue is not reproduced in the linked code above. However it demonstrates roughly how my code was working.

Specifically, this came from a discussion on discord:

I was having an issue where a div containing a button with a hint was being hidden while the hint was active. The `ExpressionChangedAfterItHasBeenCheckedError` was being thrown and the error was pointing to the `ngFor` inside the `tui-hints-host` component.

From discord, @waterplea

> I suppose we need something like rx-angular push pipe, rather than async pipe in all those hosts, because since they are parallel views to the content — it might so happen that they are already checked at the time pipe calls markForCheck and it doesn't do anything. I believe I saw something like that with dialogs. Can you raise an issue quoting me in its text?

### Angular version

15.x

### Taiga UI version

3.26.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by evantrimboli**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #4473

### CODE REVIEW

File: projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.component.ts [hunk 1]
```diff
@@ -1,11 +1,17 @@
...
+    Inject,
+    Self,
+} from '@angular/core';
+import {TUI_WINDOW_HEIGHT, TuiDestroyService} from '@taiga-ui/cdk';
 import {TUI_ANIMATION_OPTIONS, tuiFadeIn, tuiSlideInTop} from '@taiga-ui/core';
 import {Observable} from 'rxjs';
-
 import {TuiSheet} from '../../sheet';
 import {TuiSheetService} from '../../sheet.service';
+import {takeUntil} from 'rxjs/operators';
```
Comment (waterplea) [inline projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.component.ts:14]: Looks like you need to run lint fix to order imports. It should have been ran automatically in precommit hook. Don't skip them :)

File: projects/cdk/components/alert-host/alert-host.component.ts [hunk 2]
```diff
@@ -23,10 +27,23 @@ import {Observable} from 'rxjs';
     encapsulation: ViewEncapsulation.None,
 })
 export class TuiAlertHostComponent<T extends TuiDialog<unknown, unknown>> {
+    public alerts: readonly (readonly T[])[] = [];
```
Comment (waterplea) [inline projects/cdk/components/alert-host/alert-host.component.ts:30]: I think there's a lint rule for such types to be written as `ReadonlyArray<readonly T[]>`. We only use `readonly` modifier for simple array types, otherwise it becomes hard to read.

File: projects/cdk/components/dialog-host/dialog-host.component.ts [hunk 3]
```diff
@@ -33,22 +43,42 @@ const isFakeHistoryState = (
...
 export class TuiDialogHostComponent<T extends TuiDialog<unknown, unknown>> {
-    readonly dialogs$ = combineLatest(this.dialogsByType).pipe(
-        map(allTypesDialogs =>
-            new Array<T>()
-                .concat(...allTypesDialogs)
-                .sort((a, b) => a.createdAt - b.createdAt),
-        ),
-    );
+    public dialogs: readonly T[] = [];
+    public isDialogClosesOnBack = defaultClosesOnBack;
```
Comment (waterplea) [inline projects/cdk/components/dialog-host/dialog-host.component.ts:47]: You can keep initial implementation of this. It is never changing amid change detection cycle, unlike dialogs list, so it will not present that issue.

File: projects/cdk/components/dialog-host/dialog-host.component.ts [hunk 4]
```diff
@@ -33,22 +43,42 @@ const isFakeHistoryState = (
...
-    ) {}
+        @Self() @Inject(TuiDestroyService) destroy$: Observable<void>,
+        @Inject(ChangeDetectorRef) cdr: ChangeDetectorRef,
+    ) {
+        // Due to this view being parallel to app content, `markForCheck` from `async` pipe
+        // can happen after view was checked, so calling `detectChanges` instead
+        combineLatest(dialogsByType)
+            .pipe(
+                map(arr =>
+                    new Array<T>()
```
Comment (waterplea) [inline projects/cdk/components/dialog-host/dialog-host.component.ts:64]: What's the point of `new Array<T>().concat`? Why not just `[...arr]`?

File: projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.component.ts (hunk 1 above)
Comment (evantrimboli) [reply projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.component.ts:14]: I didn't skip them. Seems like whatever is setup didn't work for me. Maybe because I'm running Windows.

File: projects/cdk/components/dialog-host/dialog-host.component.ts (hunk 4 above)
Comment (evantrimboli) [reply projects/cdk/components/dialog-host/dialog-host.component.ts:64]: `[...arr]` wouldn't flatten the array properly. I had originally used `arr.flat()` however at build time it threw an error because it's only targeting ES2019.

File: projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.template.html [hunk 5]
```diff
@@ -1,6 +1,6 @@
-<ng-container *ngIf="service.sheets$ | async as items">
+<ng-container *ngIf="sheets.length > 0">
```
Comment (waterplea) [inline projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.template.html:1]: We do not need this `ng-container` and `*ngIf`

File: projects/cdk/components/alert-host/alert-host.component.ts [hunk 6]
```diff
@@ -1,16 +1,20 @@
...
+    ChangeDetectorRef,
     Component,
     Inject,
     INJECTOR,
     Injector,
+    Self,
     ViewEncapsulation,
 } from '@angular/core';
 import {TUI_PARENT_ANIMATION} from '@taiga-ui/cdk/constants';
+import {TuiDestroyService} from '@taiga-ui/cdk/services/destroy.service';
```
Comment (waterplea) [inline projects/cdk/components/alert-host/alert-host.component.ts:12]: To fix build please change that entry point to `@taiga-ui/cdk/services`

File: projects/cdk/components/dialog-host/dialog-host.component.ts [hunk 7]
```diff
@@ -1,11 +1,19 @@
...
+    ChangeDetectorRef,
+    Component,
+    Inject,
+    InjectionToken,
+    Self,
+} from '@angular/core';
 import {Title} from '@angular/platform-browser';
 import {HISTORY} from '@ng-web-apis/common';
 import {TUI_PARENT_ANIMATION} from '@taiga-ui/cdk/constants';
+import {TuiDestroyService} from '@taiga-ui/cdk/services/destroy.service';
```
Comment (waterplea) [inline projects/cdk/components/dialog-host/dialog-host.component.ts:12]: Same here

File: projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.template.html (hunk 5 above)
Comment (evantrimboli) [reply projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.template.html:1]: What about the overlay? Without the container it would always render that and it has a reference to `sheets[0]`.

Comment (waterplea) [reply projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.template.html:1]: It is hidden with CSS unless there is a Sheet with overlay visible.

**Comment by waterplea** [comment]
Looks like you forgot to add TuiDestroyService to providers for all the hosts.

**Comment by waterplea** [comment]
Looks like you cannot run `detectChanges` inside constructor and all those streams emit synchronously:
https://stackoverflow.com/questions/65712096/how-to-fix-error-assertion-error-should-be-run-in-update-mode-expected-fals
Moving to `ngOnInit` should solve this issue.

**Review by waterplea — APPROVED** [review]
Thank you for the contribution 👍

**Review by nsbarsukov — APPROVED** [review]
