### PR TITLE
chore: fix some styling issues

### LINKED ISSUE #3642: 🐞 - link component with icon
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

_No response_

### Is this issue blocking you?

Non-Blocking

### Description

link component from core has icon and distance between so distant, because icon 24px.

### Angular version

15.0.4

### Taiga UI version

3.15.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### LINKED ISSUE #3677: 🐞 - Иконка pseudo link при наведении на мгновение вспыхиывает
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-4sztjp?file=src/app/app.component.html

### Is this issue blocking you?

Non-Blocking

### Description

Если ссылку с иконкой расположить на тёмном фоне, то при наведение иконка на мгновение становится ярче ("вспыхивает") потом гаснет синхронно с ссылкой: https://stackblitz.com/edit/angular-4sztjp?file=src/app/app.component.html

### Angular version

12.2.17

### Taiga UI version

3.17.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by waterplea**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3642
Closes #3677

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/demo/src/modules/components/link/link.component.ts [hunk 1]
```diff
@@ -44,7 +44,9 @@ export class ExampleTuiLinkComponent {
 
     icon = '';
 
-    readonly iconVariants = ['tuiIconStarLarge', 'tuiIconMapPinLarge'];
+    readonly iconVariants = ['tuiIconStarLarge', 'tuiIconMapPinLarge', 'tuiIconMapPin'];
 
     iconAlign: TuiHorizontalDirection = this.iconAlignValues[0];
+
+    size = '1.5rem';
```
Comment (MarsiBarsi) [inline projects/demo/src/modules/components/link/link.component.ts:51]: nit: dont we have `rem(value)` wrap as `px(value)`?

**Review by MarsiBarsi — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/demo/src/modules/components/link/link.component.ts (hunk 1 above)
Comment (waterplea) [reply projects/demo/src/modules/components/link/link.component.ts:51]: I think we don't. But in reality we would also bind `[style.--tui-link-icon-size.rem]`, so it doesn't matter. That's external, it's up to people using Taiga UI.
