### PR TITLE
fix(kit): `InputPhoneInternational` change `Gabon` phone pattern

### LINKED ISSUE #4198: 🚀 -  Some countries can't insert their phone number on InputPhoneInternational
### Description

Costa de Marfil needs 9 digits
Gabon needs 9 digits
Chad needs 9 digits

### PR DESCRIPTION
**Pull request by splincode**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #4198

### CODE REVIEW

File: projects/kit/components/input-phone-international/tokens/countries-masks.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ export const TUI_COUNTRIES_MASKS: InjectionToken<Record<TuiCountryIsoCode, strin
             [TuiCountryIsoCode.FK]: `+500#####`,
             [TuiCountryIsoCode.FM]: `+691###-####`,
             [TuiCountryIsoCode.FR]: `+33 ## ## ## ## ##`,
-            [TuiCountryIsoCode.GA]: `+241#-##-##-##`,
+            [TuiCountryIsoCode.GA]: `+241##-##-##-##`,
```
Comment (splincode) [inline projects/kit/components/input-phone-international/tokens/countries-masks.ts:73]: `Gabon` format is `+241 XX XX XX XX` (+241 and 8 digits): https://en.wikipedia.org/wiki/Telephone_numbers_in_Gabon#:~:text=Calling%20formats&text=To%20call%20Gabon%2C%20the%20following,XX%20%2D%20calling%20from%20outside%20Gabon

**Review by waterplea — APPROVED** [review]
