### PR TITLE
fix(kit): `ComboBox` fix initial `search` emit

### LINKED ISSUE #1421: 🐞 - `searchChange` doesn't emit in ComboBox if change value to empty string at the first time
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-ehvrlx

### Description

When you select ComboBox input at the first time and change value to empty string, it doesn't trigger searchChange function

### Angular version

13

### Taiga UI version

2.26.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### LINKED ISSUE #1444: 🐞 - documentRef.createRange is not a function at new TuiLineClampDirective on server side (SSR)
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

_No response_

### Description

When rendering a `<tui-line-clamp>` on server side, I get the following error: `documentRef.createRange is not a function`.

### Angular version

13.2.0

### Taiga UI version

2.35.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by waterplea**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1444
Closes #1421

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: projects/addon-editor/directives/design-mode/design-mode.directive.ts [hunk 1]
```diff
@@ -349,7 +349,7 @@ export class TuiDesignModeDirective
     }
 
     private updateHeight() {
-        if (!this.documentRef) {
+        if (!this.documentRef || !this.documentRef.createRange) {
```
Comment (splincode) [inline projects/addon-editor/directives/design-mode/design-mode.directive.ts:352]: why not `if (!this.documentRef?.createRange) {`

**Review by splincode — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/kit/components/line-clamp/line-clamp.directive.ts [hunk 2]
```diff
@@ -39,6 +39,7 @@ export class TuiLineClampDirective {
     ) {
         if (
             cssRef.supports('-webkit-line-clamp', '1') ||
+            !documentRef.createRange ||
```
Comment (splincode) [inline projects/kit/components/line-clamp/line-clamp.directive.ts:42]: I think just in case

`!documentRef?.createRange`

File: projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts [hunk 3]
```diff
@@ -145,15 +160,18 @@ export class TuiDropdownSelectionDirective
...
 
                 const valid =
                     contained &&
-                    (!this.visibilityHandler || this.visibilityHandler(this.range));
+                    (!this.visibilityHandler ||
+                        !this.range ||
+                        this.visibilityHandler(this.range));
 
-                this.toggleDropdownBox(valid || this.inDropdown(range));
+                this.toggleDropdownBox(!!range && (valid || this.inDropdown(range)));
```
Comment (splincode) [inline projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts:174]: what do you think about more explicit?

```ts
const visible = !!range && (valid || this.inDropdown(range));

this.toggleDropdownBox(visible);
```

File: projects/kit/components/line-clamp/line-clamp.directive.ts (hunk 2 above)
Comment (waterplea) [reply projects/kit/components/line-clamp/line-clamp.directive.ts:42]: No, here we always have document.
