### PR TITLE
fix(kit): `InputNumber` apply caret fix for ios

### LINKED ISSUE #1552: 🐞 `InputNumber` incorrect behavior with [precision] = 'never' flag
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

Caret moves in wrong position on IPhone/IPad when using precision 'never' flag

### Angular version

9>

### Taiga UI version

2.38.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1552 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/kit/components/input-number/input-number.component.ts [hunk 1]
```diff
@@ -188,6 +190,7 @@ export class TuiInputNumberComponent
                 this.numberFormat.thousandSeparator,
                 nativeFocusableElement,
                 allowNegative,
+                this.isIOS,
```
Comment (splincode) [inline projects/kit/components/input-number/input-number.component.ts:193]: please, check the correctness of work `input-slider.ts` on demo

Comment (vladimirpotekhin) [reply projects/kit/components/input-number/input-number.component.ts:193]: behavior incorrect, but same behavior in main demo. I think this is a separate bug

Comment (splincode) [reply projects/kit/components/input-number/input-number.component.ts:193]: could you fix it in this PR or would you like it in a separate one?

**Review by splincode — APPROVED** [review]
