### PR TITLE
fix(addon-editor): support styles without paragraph for lists

### LINKED ISSUE #2062: После обновления taiga-ui/addon-editor генерируется другой html для списков из-за чего слетает нумерация/маркеры🐞 -
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/editor-new и https://taiga-ui.dev/components/editor

### Is this issue blocking you?

Non-Blocking

### Description

Можно воспроизвести [здесь](https://taiga-ui.dev/components/editor-new)  и [здесь](https://taiga-ui.dev/components/editor) 

Новая версия эдитора генерирует вот такой html для списка: `<ul><li><p>12345</p></li></ul>`:

Снимок экрана 2022-07-06 в 16 38 01

Старая версия такой: `<ul><li>12345</li></ul>`:

Снимок экрана 2022-07-06 в 16 37 33
 
Наши списки хранятся в БД, из-за этого при обновлении на новую версию эдитора, у них пропадает нумерация/маркеры 

### Angular version

11.2.11

### Taiga UI version

2.47.0 и 2.50.2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2062

## What is the new behavior?

4-1-bullet-and-ordered-list snap
4-2-bullet-and-ordered-list snap

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by waterplea — APPROVED** [review]

File: projects/addon-editor/constants/tiptap-editor-styles.ts [hunk 1]
```diff
@@ -51,7 +51,7 @@ export const tiptapEditorStyles = `
     counter-reset: counter;
 }
 
-.tui-editor-socket ol li p:first-child:before {
+.tui-editor-socket ol li:before {
```
Comment (vladimirpotekhin) [inline projects/addon-editor/constants/tiptap-editor-styles.ts:54]: if the list item contains two paragraphs, the circle should stay before first one

Comment (splincode) [reply projects/addon-editor/constants/tiptap-editor-styles.ts:55]: fixed

**Review by vladimirpotekhin — APPROVED** [review]
