### PR TITLE
fix(addon-charts): remove location origin from mask

### LINKED ISSUE #3109: 🐞 - `PieChart` / `RingChart` mask doesn't work on `/next/` demo
### Which @taiga-ui/* package(s) are the source of the bug?

addon-charts

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/next/components/ring-chart 

### Is this issue blocking you?

Blocking

### Description

В версии 3.10.0 выводится корректно, в next не корректно

### Angular version

14.x.x

### Taiga UI version

next

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3109

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/addon-charts/components/line-chart/line-chart.component.ts [hunk 1]
```diff
@@ -101,7 +102,8 @@ export class TuiLineChartComponent {
     constructor(
         @Inject(TuiIdService) idService: TuiIdService,
         @Inject(NgZone) private readonly ngZone: NgZone,
-        @Inject(Location) private readonly locationRef: Location,
+        @Inject(NgLocation) private readonly locationNg: NgLocation,
```
Comment (vladimirpotekhin) [inline projects/addon-charts/components/line-chart/line-chart.component.ts:105]: nit: `ngLocation: NgLocation`

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/addon-charts/components/line-chart/line-chart.component.ts (hunk 1 above)
Comment (splincode) [reply projects/addon-charts/components/line-chart/line-chart.component.ts]: fixed

**Review by nsbarsukov — APPROVED** [review]
