### PR TITLE
fix(kit): fix reopening nested dropdown

### LINKED ISSUE #3249: 🐞 - Sub dropdown after close gets additionally reopened and closed in left top corner
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-t2w7nv?file=src%2Fapp%2Fapp.component.ts

### Is this issue blocking you?

Blocking

### Description

The same issue which fixed before https://github.com/Tinkoff/taiga-ui/issues/997. Now we observe it again.

### Angular version

14.2.6

### Taiga UI version

3.13.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?
I found that reopening happens when we click on the submenu item faster than [this debounceTime](https://github.com/Tinkoff/taiga-ui/blob/main/projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts#L139) in `DataListDropdownManager`. The child data list recreates when parent data-list already closed. 

Closes #3249 

## What is the new behavior?
takeUntil stops the stream when the parent data-list closes

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts [hunk 1]
```diff
@@ -36,6 +41,10 @@ export class TuiDataListDropdownManagerDirective implements AfterViewInit {
     @ContentChildren(TuiDropdownDirective, {read: ElementRef, descendants: true})
     private readonly elements: QueryList<ElementRef<HTMLElement>> = EMPTY_QUERY;
 
+    constructor(
+        @Self() @Inject(TuiDestroyService) private readonly destroy$: TuiDestroyService,
+    ) {}
+
     ngAfterViewInit(): void {
         this.right$.subscribe(index => {
```
Comment (waterplea) [inline projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts:49]: You should add it here too. There was no `takeUntil` in this component, because it comes from `@QueryList` which completes after component is destroyed, but we did not consider `shareReplay`.

Comment (vladimirpotekhin) [reply projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts]: done ✔️

**Review by nsbarsukov — APPROVED** [review]

**Review by splincode — APPROVED** [review]
