### PR TITLE
fix(core): `DropdownContext` fix closing (ng14)

### LINKED ISSUE #3356: 🐞 - Dropdown context menu does not close
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-323fzw?file=src%2Fapp%2Fapp.component.ts

### Is this issue blocking you?

Non-Blocking

### Description

After opening the dropdown context menu, when you click outside to close it, it does not close and goes into a state where you can't select any options from the menu.

### Angular version

14.2.12

### Taiga UI version

3.15

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3356 

## What is the new behavior?

now it works in ng14+

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown-context.directive.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ export class TuiDropdownContextDirective extends TuiDriver implements TuiRectAcc
         this.stream$.next(true);
     }
 
-    @HostListener('document:click.silent', ['$event.target'])
```
Comment (waterplea) [inline projects/core/directives/dropdown/dropdown-context.directive.ts:41]: It should remain silent, otherwise it triggers change detection on every click on the document. Instead please add `@shouldCall` decorator and move if condition to it. It's a decorator from `@tinkoff/ng-event-plugins`, it takes a predicate as an argument and if it returns `true`, calls the method insize `ngZone.run`. You can access `this` inside that predicate.

**Review by waterplea — CHANGES_REQUESTED** [review]

File: projects/core/directives/dropdown/dropdown-context.directive.ts (hunk 1 above)
Comment (vladimirpotekhin) [reply projects/core/directives/dropdown/dropdown-context.directive.ts:41]: cool, thx

**Review by waterplea — APPROVED** [review]
