### PR TITLE
fix(kit): `InputPhone` cut value by max phone length

### LINKED ISSUE #3066: 🐞 - FieldError displaying incorrectly on repeating inputs with max input length reached
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/pipes/field-error#formArray

### Is this issue blocking you?

Non-Blocking

### Description

In `tui-input-phone` (maybe in other inputs, too) when you try to write past the character limit with the `tui-error` visible, it generates a lot of `tuiHeightCollapse` blocks.

https://user-images.githubusercontent.com/47535336/201718040-6a701d32-61b5-4bc3-b0ad-448fa44fee1e.mp4

### Angular version

14.2.2

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?
value is truncated before updating control

Closes #3066

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/kit/components/input-phone/input-phone.component.ts [hunk 1]
```diff
@@ -216,7 +216,9 @@ export class TuiInputPhoneComponent
     onValueChange(value: string): void {
         value = value === `` ? this.countryCode : value;
 
-        const parsed = isText(value) ? value : value.replace(TUI_MASK_SYMBOLS_REGEXP, ``);
+        const parsed = isText(value)
```
Comment (splincode) [inline projects/kit/components/input-phone/input-phone.component.ts:219]: Could you add unit test or cypress test?

Comment (vladimirpotekhin) [reply projects/kit/components/input-phone/input-phone.component.ts:219]: done 👍

**Review by splincode — APPROVED** [review]

**Review by nsbarsukov — APPROVED** [review]
