### PR TITLE
fix(kit): prevent expression changed exception in `line-clamp`

### LINKED ISSUE #404: [BUG]  LineClamp spits ChangesAfterChecked
# 🐞 Bug report

### Description

LineClamp gives ChangedAfterChecked error while instantiating. Says max-height was null and became 24px. No difference if line height input set or not.

### Reproduction

Filing a bug from the phone, @waterplea you said in Discord that you see where the issue is in sources

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #404

## What is the new behavior?

image

image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by splincode** [comment]
@nsbarsukov @vladimirpotekhin please, review me)

File: projects/demo/src/modules/components/line-clamp/examples/3/index.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+    templateUrl: './index.html',
+    styleUrls: ['./index.less'],
+    changeDetection,
+    encapsulation,
+})
+export class TuiLineClampExample3 {
+    constructor(@Inject(WINDOW) private readonly windowRef: Window) {}
+
+    getDynamicLineHeight(element: HTMLDivElement): number {
+        return parseInt(this.windowRef.getComputedStyle(element).lineHeight);
```
Comment (waterplea) [inline projects/demo/src/modules/components/line-clamp/examples/3/index.ts:17]: That's probably too heavy for a getter 🤔

**Review by waterplea — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/demo/src/modules/components/line-clamp/examples/3/index.ts (hunk 1 above)
Comment (splincode) [reply projects/demo/src/modules/components/line-clamp/examples/3/index.ts:17]: Do you think it should be improved?

**Review by waterplea — APPROVED** [review]
