### PR TITLE
fix(addon-charts): `RingChart` fix mask url

### LINKED ISSUE #4769: 🐞 - Not working mask in RingChart inner SVG
### Playground Link

https://taiga-ui.dev/charts/ring-chart/

### Description

**Reproduction:** open https://taiga-ui.dev/charts/ring-chart/ (with slash at end) directly

**Expected result:** normal looking RingChart

**Actual result:** PieChart-like appearance, inner content is not visible because it is placed under svg
image

**Possible problem** - invalid path to mask in generated inner svg. Seems to work okay after deleting path prefix in url (see examples below):
image
image

### Angular version

12.2.17

### Taiga UI version

3.33.1 (also v2)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by waterplea**
## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #4769

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/addon-charts/components/pie-chart/pie-chart.component.ts [hunk 1]
```diff
@@ -104,9 +99,7 @@ export class TuiPieChartComponent {
     }
 
     get mask(): string | null {
```
Comment (nsbarsukov) [inline projects/addon-charts/components/pie-chart/pie-chart.component.ts:101]: Should we link this PR to this issue ?
https://github.com/Tinkoff/taiga-ui/issues/4769
