### PR TITLE
fix(kit): `Slider` incorrect calculations with `[ngModel]` + `[keySteps]`

### LINKED ISSUE #2259: 🐞 - `InputSlider` bug with initial control value > 100
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/input-slider-initial-value-bug?file=src/app/app.component.ts

### Is this issue blocking you?

Blocking

### Description

```ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: `my-app`,
  template: `
    <tui-root>
        <tui-input-slider
            [min]="min"
            [max]="max"
            [formControl]="control"
        ></tui-input-slider>
    </tui-root>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  readonly min = 0;
  readonly max = 120_000;

  readonly control = new FormControl(101); // ERROR
  // readonly control = new FormControl(100); // NO ERROR
}

```

### Error
```
TuiInputSliderComponent.html:1 ERROR
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at __read (tslib.es6.js:137:46)
    at Object.tuiPercentageToKeyStepValue (key-steps.ts:20:12)
    at TuiSliderKeyStepsDirective.get [as controlValue] (slider-key-steps.directive.ts:77:16)
    at Object.eval [as updateRenderer] (TuiInputSliderComponent.html:39:5)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:414:19)
    at checkAndUpdateView (view.ts:381:12)
    at callViewAction (view.ts:628:11)
    at execComponentViewsAction (view.ts:572:7)
    at checkAndUpdateView (view.ts:383:3)
    at callViewAction (view.ts:628:11)
```

### Angular version

any

### Taiga UI version

2.56.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?
Closes #2259

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/kit/components/slider/slider.component.ts [hunk 1]
```diff
@@ -109,6 +109,7 @@ export class TuiSliderComponent {
         @Inject(TUI_SLIDER_OPTIONS) readonly options: TuiSliderOptions,
         @Inject(ElementRef) readonly elementRef: ElementRef<HTMLInputElement>,
         @Inject(USER_AGENT) private readonly userAgent: string,
+        @Inject(TUI_SLIDER_HAS_KEY_STEPS) private readonly hasKeySteps: boolean,
```
Comment (vladimirpotekhin) [inline projects/kit/components/slider/slider.component.ts:112]: can we just optional inject directive without extra token?

Comment (nsbarsukov) [reply projects/kit/components/slider/slider.component.ts:112]: Unfortunately, it will cause cyclic imports :((

https://github.com/Tinkoff/taiga-ui/blob/e35eea87afcb15935e780bca504dab785dc6d36d/projects/kit/components/slider/helpers/slider-key-steps.directive.ts#L32

Comment (nsbarsukov) [reply projects/kit/components/slider/slider.component.ts:112]: I tried even with `forwardRef(...)`
```ts
       @Inject(forwardRef(() => TuiSliderKeyStepsDirective)) private readonly hasKeySteps: unknown,
```

Comment (nsbarsukov) [reply projects/kit/components/slider/slider.component.ts:112]:
```
core.js:6241 ERROR Error: Circular dep for TuiSliderComponent
    at getNodeInjectable (core.js:5981:1)
    at searchTokensOnInjector (core.js:5908:1)
    at getOrCreateInjectable (core.js:5812:1)
    at Module.ɵɵdirectiveInject (core.js:21157:1)
    at NodeInjectorFactory.TuiSliderKeyStepsDirective_Factory [as factory] (slider-key-steps.directive.ts:87:27)
    at getNodeInjectable (core.js:5993:1)
    at searchTokensOnInjector (core.js:5908:1)
    at getOrCreateInjectable (core.js:5812:1)
    at Module.ɵɵdirectiveInject (core.js:21157:1)
    at NodeInjectorFactory.TuiSliderComponent_Factory [as factory] 
```

Comment (vladimirpotekhin) [reply projects/kit/components/slider/slider.component.ts:112]: oh, got it ( sorry

Comment (nsbarsukov) [reply projects/kit/components/slider/slider.component.ts:112]: I have an idea
```ts
@Inject(Injector) private readonly injector: Injector,
//...
this.injector.get(TuiSliderKeyStepsDirective, null)
```

Give me a moment to try it :D

Comment (nsbarsukov) [reply projects/kit/components/slider/slider.component.ts:112]: @vladimirpotekhin I did not believe in it... but it works!

I will double check everything and push new commit later.

Comment (vladimirpotekhin) [reply projects/kit/components/slider/slider.component.ts:112]: wow cool 😎

Comment (nsbarsukov) [reply projects/kit/components/slider/slider.component.ts]: fixed

I've checked that it 
✅ works in `main`-branch (angular 9)
✅ works in `v3.x`-branch (angular 12)

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/kit/components/slider/slider.component.ts [hunk 2]
```diff
@@ -67,10 +69,10 @@ export class TuiSliderComponent {
     }
 
     get value(): number {
-        const {elementRef, control} = this;
-        const noKeySteps = !elementRef.nativeElement.hasAttribute(`data-key-steps`);
+        const {elementRef, control, injector} = this;
+        const hasKeySteps = Boolean(injector.get(TuiSliderKeyStepsDirective, null));
```
Comment (waterplea) [inline projects/kit/components/slider/slider.component.ts:73]: We should probably memoize it, right now we rely on `get` operation of the `Injector` being getter-level fast which we cannot be certain of.

Comment (nsbarsukov) [reply projects/kit/components/slider/slider.component.ts]: fixed

File: projects/kit/components/slider/slider.component.ts [hunk 3]
```diff
@@ -100,6 +102,11 @@ export class TuiSliderComponent {
         return isEdgeOlderThan(CHROMIUM_EDGE_START_VERSION, this.userAgent);
     }
 
+    @tuiPure
+    get hasKeySteps(): boolean {
+        return Boolean(this.injector.get(TuiSliderKeyStepsDirective, null));
```
Comment (nsbarsukov) [inline projects/kit/components/slider/slider.component.ts:107]: I cannot just declare this constant as 
```ts
export class TuiSliderComponent {
    private readonly hasKeySteps = Boolean(
        this.injector.get(TuiSliderKeyStepsDirective, null)
    );
    // ...
}
```

because it will cause
```
ERROR Error: Circular dep for TuiSliderComponent
```

**Review by vladimirpotekhin — APPROVED** [review]

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
