### PR TITLE
fix(kit): `Tabs` can't detect active tab during SSR

### LINKED ISSUE #3393: 🐞 - `Tabs` can't detect active tab during SSR
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Is this issue blocking you?

Non-Blocking

### Reproduction
1. Run `nx serve-ssr`
2. Disable Javascript for browser
3. Open any documentation page with  `<tui-tabs />` (for example, `/components/action`)

tabs

<br />

### Problem explanation
`Tabs` uses `TuiRouterLinkActiveService` inside to detect active tab and dispatch custom event:
https://github.com/Tinkoff/taiga-ui/blob/16747a7da75deeafe3c5cd96fd9c077c6ba57c9f/projects/kit/components/tabs/tab/tab.providers.ts#L50-L52

And `TuiRouterLinkActiveService` has this line:
https://github.com/Tinkoff/taiga-ui/blob/16747a7da75deeafe3c5cd96fd9c077c6ba57c9f/projects/core/services/router-link-active.service.ts#L15-L19

**But `animationFrame$` [never emits any value](https://github.com/ng-web-apis/universal/blob/21db5a0ec7ffb271fb55dc6ae4ec2c50c19cc39d/projects/universal/src/constants/universal-animation-frame.ts#L5-L8) during SSR!**
(and `TUI_TAB_ACTIVATE` is never dispatched during SSR)

Okay, it is not a big problem. We can do this workaround for SSR:
```ts
merge(timer(0), animationFrame$).pipe( ...)
```

Now, code with dispatching custom event `TUI_TAB_ACTIVATE` executes
https://github.com/Tinkoff/taiga-ui/blob/16747a7da75deeafe3c5cd96fd9c077c6ba57c9f/projects/kit/components/tabs/tab/tab.providers.ts#L50-L52

**But it does NOT trigger this `@HostListener('${TUI_TAB_ACTIVATE}.stop')` during SSR**. It works only for client side =/
https://github.com/Tinkoff/taiga-ui/blob/16747a7da75deeafe3c5cd96fd9c077c6ba57c9f/projects/kit/components/tabs/tabs.directive.ts#L40-L41

### Angular version

12

### Taiga UI version

3.15.0

### PR DESCRIPTION
**Pull request by nsbarsukov**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3393 

SSR returns:
before

## What is the new behavior?
SSR returns:
after

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: projects/kit/components/tabs/tabs.directive.ts [hunk 1]
```diff
@@ -37,10 +37,12 @@ export class TuiTabsDirective implements AfterViewChecked {
         return this.tabs[this.activeItemIndex] || null;
     }
 
-    @HostListener(`${TUI_TAB_ACTIVATE}.stop`, ['$event.target'])
-    onActivate(element: HTMLElement): void {
+    @HostListener(TUI_TAB_ACTIVATE, ['$event', '$event.target'])
+    onActivate(event: Event, element: HTMLElement): void {
         const index = this.tabs.findIndex(tab => tab === element);
 
+        event.stopPropagation();
```
Comment (nsbarsukov) [inline projects/kit/components/tabs/tabs.directive.ts:44]: https://github.com/Tinkoff/taiga-ui/issues/3393#issuecomment-1377291040

Comment (nsbarsukov) [reply projects/kit/components/tabs/tabs.directive.ts:44]: https://github.com/Tinkoff/ng-event-plugins/issues/53

**Review by vladimirpotekhin — APPROVED** [review]
