### PR TITLE
fix(core): `DescribedByDirective` fix hint visibility

### LINKED ISSUE #1287: 🐞 - Clicking on tooltip text breaks it in `TextArea`
### Which @taiga-ui/* package(s) are the source of the bug?

core, kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/text-area#extra-chars-highlight

### Description

Steps:

1. Click on tooltip icon inside texarea.
2. Click on text in hint

Result:
Tooltip closes and won't open again

### Angular version

9.1.12

### Taiga UI version

2.31.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?
desribedBy directive removes hint first time due to blur event

Closes #1287 

## What is the new behavior?
desribedBy directive removes hint on blur event only after focus from keyboard 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/core/directives/described-by/described-by.providers.ts [hunk 1]
```diff
@@ -31,27 +31,34 @@ export function describedByFactory(
     focusVisible$: Observable<boolean>,
     {nativeElement}: ElementRef<HTMLElement>,
 ): Observable<boolean> {
-    return merge(
-        focusVisible$.pipe(
+    return focusVisible$
```
Comment (splincode) [inline projects/core/directives/described-by/described-by.providers.ts:34]: Could you add an e2e test for this please?

**Review by splincode — APPROVED** [review]

File: projects/core/directives/described-by/described-by.providers.ts [hunk 2]
```diff
@@ -31,27 +31,34 @@ export function describedByFactory(
...
+        .pipe(
             filter(v => v),
```
Comment (waterplea) [inline projects/core/directives/described-by/described-by.providers.ts:36]: nit: filter(Boolean) :)

File: projects/core/directives/described-by/described-by.providers.ts [hunk 3]
```diff
@@ -31,27 +31,34 @@ export function describedByFactory(
...
-                    tap(event => {
-                        event.stopPropagation();
-                    }),
-                    mapTo(false),
-                    startWith(true),
+                merge(
+                    typedFromEvent(nativeElement, 'keydown').pipe(
+                        filter(({key}) => key === 'Escape'),
+                        take(1),
+                        tap(event => {
```
Comment (waterplea) [inline projects/core/directives/described-by/described-by.providers.ts:53]: `stopPropagation()`

**Review by waterplea — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
