### PR TITLE
fix(kit): `ComboBox` throws `ExpressionChangedAfterItHasBeenCheckedError`

### LINKED ISSUE #1643: 🐞 - `ComboBox` throws `ExpressionChangedAfterItHasBeenCheckedError`
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/combobox-paste-error?file=src/app/app.component.ts

### Description

1. Open stackblitz example
2. Copy `1` to clipboard (ctrl + c)
3. Paste it to combobox text input (ctrl + v)

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.
Previous value: 'ng-pristine: true'. Current value: 'ng-pristine: false'.
```

**UPDATE:** you can just type value `1` to get error (without copy-paste).

### Angular version

any

### Taiga UI version

2.26.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by nsbarsukov**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

#### Simplified version of the bug’s reproduction:

<details>
  <summary>HTML</summary>

```html
<tui-root>
  <tui-combo-box
    [ngModel]="selectedProcedure"
    [stringify]="stringify"
    (searchChange)="onSearchProcedureChange()"
  >
    Type "1"

    <tui-data-list-wrapper
      *tuiDataList
      [items]="procedures$ | async"
    ></tui-data-list-wrapper>
  </tui-combo-box>
</tui-root>
```
</details>

<details>
  <summary>Typescript</summary>

```ts
import { Component } from '@angular/core';
import { BehaviorSubject } from 'rxjs';


@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
})
export class ExampleComponent {
  procedures$ = new BehaviorSubject<any[]>([]);
  selectedProcedure: any = null;

 onSearchProcedureChange(): void {
    this.procedures$.next([
      { id: '1', name: 'one' },
      { id: '2', name: 'two' },
    ]);
  }

  stringify(procedure: any): string {
    return procedure?.id;
  }
}

```
</details>

#### What's happening
1. When we type "1", this function is triggered:
https://github.com/Tinkoff/taiga-ui/blob/d82ab19a9598ec47469b0d218b514c4ddd78263e/projects/kit/components/combo-box/combo-box.component.ts#L181-L198

Controller is not changed (it was `null` and after this function it is still `null`). It is still pristine.

No item is selected because `procedures$` (inside our `ExampleComponent`) is empty. After that function `onSearchProcedureChange` (inside our `ExampleComponent`) is triggered and fills `procedures$` with two new items (prop `[items]` inside `<tui-data-list-wrapper />` changes).

2. **Tick happens!** (all next steps happens in the same tick).

3.  Angular evaluates `pristine`-status as `true` inside this [built-in form-controller directive](https://github.com/angular/angular/blob/main/packages/forms/src/directives/ng_control_status.ts#L99).

4. Angular renders new `SelectOption`-s and their `ngOnInit` were triggered:
https://github.com/Tinkoff/taiga-ui/blob/68ab06940351262f9468165d5c4a3aa1046d5696/projects/kit/components/select-option/select-option.component.ts#L52-L56

They invoke `checkOption`-functions of the parent component.
https://github.com/Tinkoff/taiga-ui/blob/d82ab19a9598ec47469b0d218b514c4ddd78263e/projects/kit/components/combo-box/combo-box.component.ts#L148-L155

And `this.updateValue(option)` makes control `dirty`.

5. Angular starts its  next digest cycle with checks (dev-mode only). At the start of the change-detection cycle `pristine` was `true` but at the end it is `false`. Angular throws error.

Closes #1643

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/kit/components/select-option/select-option.component.ts [hunk 1]
```diff
@@ -50,9 +50,18 @@ export class TuiSelectOptionComponent<T> implements OnInit {
...
-            this.host.checkOption(this.option.value);
-        }
+        /**
+         * This would cause changes inside already checked parent component (during the same change detection cycle),
+         * and it might cause ExpressionChanged error due to potential HostBinding
+         * (for example, inside {@link https://github.com/angular/angular/blob/main/packages/forms/src/directives/ng_control_status.ts#L99 NgControlStatus}).
+         * Microtask keeps it in the same frame but allows change detection to run.
+         */
+        // eslint-disable-next-line @typescript-eslint/no-floating-promises
+        Promise.resolve().then(() => {
```
Comment (splincode) [inline projects/kit/components/select-option/select-option.component.ts:60]: what do you think about `runOutsideAngular`?

**Review by waterplea — APPROVED** [review]
