### PR TITLE
fix(kit): `InputPhoneInternational` fix paste/drop without plus

### LINKED ISSUE #1296: 🐞 - `InputPhoneInternational` bugs
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

_No response_

### Description

1. can't paste number without +
2. onChange emits incorrect phone when countryIsoCode and ngModel updated at the same time

### Angular version

9>

### Taiga UI version

2.32

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1296

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/kit/components/input-phone-international/input-phone-international.component.ts [hunk 1]
```diff
@@ -131,9 +131,9 @@ export class TuiInputPhoneInternationalComponent
     @HostListener('paste.capture.prevent.stop', ['$event'])
     @HostListener('drop.capture.prevent.stop', ['$event'])
     onPaste(event: ClipboardEvent | DragEvent) {
-        const value = extractValueFromEvent(event);
+        const value = extractValueFromEvent(event).replace('+', '');
         const countryIsoCode = this.countries.find(countryIsoCode =>
-            value.startsWith(this.isoToCountryCode(countryIsoCode)),
+            value.startsWith(this.isoToCountryCode(countryIsoCode).replace('+', '')),
```
Comment (splincode) [inline projects/kit/components/input-phone-international/input-phone-international.component.ts:136]: Hello, what do you think about?

```ts
const value = escapeInvalidValue(extractValueFromEvent(event));

const countryIsoCode = this.countries.find(countryIsoCode =>
  escapeInvalidValue(value.startsWith(this.isoToCountryCode(countryIsoCode))
);
```

```ts
export function escapeInvalidValue(value: string): string {
 return value.replace('+', '');
}
```

`escapeInvalidValue` - not sure about that is good name

**Review by splincode — APPROVED** [review]

File: projects/kit/components/input-phone-international/input-phone-international.component.ts (hunk 1 above)
Comment (waterplea) [reply projects/kit/components/input-phone-international/input-phone-international.component.ts:136]: I think it's ok as is, it's just a few characters in one spot.

**Review by waterplea — APPROVED** [review]
