### PR TITLE
fix(cdk): support ng-add for ng14

### LINKED ISSUE #1909: 🐞 - updater is not a function
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Blocking

### Description

While adding taiga-ui to my app project, I receive an `updater is not a function` error which does not let me continue with installation.

```
λ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.0.1
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 14.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.1
@angular-devkit/build-angular   14.0.1
@angular-devkit/core            14.0.1
@angular-devkit/schematics      14.0.1
@schematics/angular             14.0.1
rxjs                            7.5.5
typescript                      4.7.3
```

```
λ ng add taiga-ui
Skipping installation: Package already installed
? Do you want to use Taiga UI dialogs? Yes
? Do you plan on using custom SVGs/icons or addon-editor? If `Yes` we will include ng-dompurify as sanitizer, read more: https://taiga-ui.dev/icon-set#sanitizer Yes
? Do you want to use Taiga UI alerts? Yes
? Choose additional packages to install addon-charts      Components for various charts, graphs and visualizations, addon-commerce    Money-related extension with currencies, credit card
inputs and validators, addon-mobile      Components and tools specific to mobile version of the app, addon-table       Interactive table component and related utilities, addon-tablebars
Group action sliding toolbar, addon-editor      Rich text editor extension with related components, addon preview     Custom fullscreen dialog to preview various content such as documents,
images etc.
    The main packages will be installed - core,cdk,kit,icons
UPDATE package.json (2052 bytes)
updater is not a function
```

### Angular version

14.0.1

### Taiga UI version

2.48.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?
ng add doesn't work with angular 14

updateWorkspace overload with only workspace arg has been removed
https://github.com/angular/angular-cli/commit/b07ccfbb1b2045d285c23dd4b654e1380892fcb2#diff-2740741169dc6046fa1273c3841fcf3812646f415c89a1f7c485165f6b74e8aaL34

Closes #1909

## What is the new behavior?
ng add works with angular 14

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/cdk/schematics/ng-add/steps/add-taiga-icons.ts [hunk 1]
```diff
@@ -13,26 +12,22 @@ const ICON_ASSETS = {
...
-    }
+        const targetOptions = getProjectTargetOptions(project, 'build');
+        const assets = targetOptions.assets as JsonArray | undefined;
 
-    return updateWorkspace(workspace);
+        if (!assets) {
+            targetOptions.assets = [ICON_ASSETS];
+        } else {
+            targetOptions.assets = [...assets, ICON_ASSETS];
+        }
```
Comment (splincode) [inline projects/cdk/schematics/ng-add/steps/add-taiga-icons.ts:31]:
```ts
targetOptions.assets = assets ? [...assets, ICON_ASSETS] : [ICON_ASSETS];
```

File: projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts [hunk 2]
```diff
@@ -10,27 +9,22 @@ const TAIGA_GLOBAL_STYLE = 'node_modules/@taiga-ui/core/styles/taiga-ui-global.l
...
+        const targetOptions = getProjectTargetOptions(project, 'build');
+        const styles = targetOptions.styles as JsonArray | undefined;
+        const taigaStyles = [TAIGA_GLOBAL_STYLE, TAIGA_THEME_STYLE];
 
-    return updateWorkspace(workspace);
+        if (!styles) {
+            targetOptions.styles = taigaStyles;
+        } else {
+            targetOptions.styles = Array.from(new Set([...taigaStyles, ...styles]));
+        }
```
Comment (splincode) [inline projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts:28]:
```ts
targetOptions.styles = styles ? Array.from(new Set([...taigaStyles, ...styles])) : taigaStyles;
```

File: projects/taiga-schematics/schematics/ng-add/steps/add-taiga-icons.ts [hunk 3]
```diff
@@ -13,26 +12,22 @@ const ICON_ASSETS = {
...
-    if (!assets) {
-        targetOptions.assets = [ICON_ASSETS];
-    } else {
-        targetOptions.assets = [...assets, ICON_ASSETS];
-    }
+        const targetOptions = getProjectTargetOptions(project, 'build');
+        const assets = targetOptions.assets as JsonArray | undefined;
 
-    return updateWorkspace(workspace);
+        if (!assets) {
```
Comment (splincode) [inline projects/taiga-schematics/schematics/ng-add/steps/add-taiga-icons.ts:27]: same
