### PR TITLE
fix(kit): combobox is cleared when you enter same value

### LINKED ISSUE #1686: 🐞 - Combobox is cleared when you enter same value as in dropdown
### Which @taiga-ui/* package(s) are the source of the bug?

core, kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/combo-box/API?tuiMode=null

### Description

When you enter a value matches the element of a dropdown, the combobox is cleared

### Angular version

11.2.13

### Taiga UI version

2.43.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1686

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/kit/components/combo-box/combo-box.component.ts [hunk 1]
```diff
@@ -183,9 +183,8 @@ export class TuiComboBoxComponent<T>
 
         const match = this.accessor?.getOptions().find(item => this.isStrictMatch(item));
 
-        if (match !== undefined) {
+        if (match) {
```
Comment (waterplea) [inline projects/kit/components/combo-box/combo-box.component.ts:186]: Value can be falsy, previous check was correct

File: projects/kit/components/combo-box/combo-box.component.ts [hunk 2]
```diff
@@ -183,9 +183,8 @@ export class TuiComboBoxComponent<T>
...
             this.updateValue(match);
-            this.updateSearch(null);
```
Comment (waterplea) [inline projects/kit/components/combo-box/combo-box.component.ts:188]: When a user picks value from the list we emit null for search so that it's clear no need to fetch serverside items for the new string value. So that's correct. Something else got broken, because it used to work properly this way.

**Review by waterplea — CHANGES_REQUESTED** [review]

File: projects/kit/components/combo-box/combo-box.component.ts (hunk 2 above)
Comment (splincode) [reply projects/kit/components/combo-box/combo-box.component.ts]: revert

File: projects/kit/components/combo-box/combo-box.component.ts (hunk 1 above)
Comment (splincode) [reply projects/kit/components/combo-box/combo-box.component.ts]: revert

**Review by waterplea — APPROVED** [review]
