### PR TITLE
fix(core): `DropdownContext` fix nested dropdowns

### LINKED ISSUE #3266: 🐞 - Context dropdown gets closed after focus inside input component of nested dropdown
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-s4je8n?file=src%2Fapp%2Fapp.component.html

### Is this issue blocking you?

Blocking

### Description

Steps: 
- open context dropdown 
- go inside nested and click on text field 
- type any text

Current:
- context dropdown gets closed

P.S. Actually [this logic](https://github.com/Tinkoff/taiga-ui/blob/74df80dd302c0fa8fdabfcaf063d2d99cc18c815/projects/core/directives/dropdown/dropdown.directive.ts#L99) to close a dropdown invoked on click, not on input change. Seems change event will trigger change detection and UI will be update after.

works well in v2: https://stackblitz.com/edit/angular-vpcdbx?file=src%2Fapp%2Fapp.component.html

### Angular version

14.2.6

### Taiga UI version

3.14.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by waterplea**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3266

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: projects/core/directives/dropdown/dropdown-context.directive.ts [hunk 1]
```diff
@@ -37,8 +41,8 @@ export class TuiDropdownContextDirective extends TuiDriver implements TuiRectAcc
     @HostListener(`document:click.silent`, [`$event.target`])
     @HostListener(`document:contextmenu.capture.silent`, [`$event.target`])
     @HostListener(`document:keydown.esc`, [`$event.currentTarget`])
-    closeDropdown(target: EventTarget): void {
-        if (!this.dropdown.dropdownBoxRef?.location.nativeElement.contains(target)) {
+    closeDropdown(target: Element): void {
+        if (!this.activeZone.contains(target)) {
```
Comment (splincode) [inline projects/core/directives/dropdown/dropdown-context.directive.ts:45]: Is it possible to add e2e for check this case?

**Review by vladimirpotekhin — APPROVED** [review]

**Review by splincode — APPROVED** [review]

File: projects/core/directives/dropdown/dropdown-context.directive.ts (hunk 1 above)
Comment (waterplea) [reply projects/core/directives/dropdown/dropdown-context.directive.ts:45]: Done
