### PR TITLE
fix(core): correct filler display for size `S` and `M`

### LINKED ISSUE #1709: tui-input-date with tuiTextfieldSize="s" not hide hint on focus, results in glitch🐞 -
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://i.imgur.com/4p2uL0h.png

### Description

When one clicks at tui-input-date element that contains inner text as hint, that hint does not hide and remains displayed above date format hint. Text hint pushes date format hind lower than form border.

### Angular version

13.1.1

### Taiga UI version

2.43.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1709

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts [hunk 1]
```diff
@@ -50,13 +50,18 @@ export class TuiValueDecorationComponent {
...
     }
 
     get filler(): string {
         const {focused, placeholder, exampleText, value, textfield} = this;
 
-        if (focused && placeholder && exampleText) {
+        const skipFiller =
+            (focused && placeholder && exampleText) ||
+            (textfield.size == 's' && !value.length) ||
+            (!textfield.placeholderRaised && textfield.size == 'm' && !value.length);
```
Comment (waterplea) [inline projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts:62]: Let's destruct `const {placeholderRaised, size} = textfield;`

File: projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts [hunk 2]
```diff
@@ -50,13 +50,18 @@ export class TuiValueDecorationComponent {
     }
 
     get value(): string {
-        return this.textfield.value;
+        return this.textfield.value || '';
```
Comment (waterplea) [inline projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts:53]: When is this fallback required?

File: projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts [hunk 3]
```diff
@@ -50,13 +50,18 @@ export class TuiValueDecorationComponent {
...
     }
 
     get filler(): string {
         const {focused, placeholder, exampleText, value, textfield} = this;
 
-        if (focused && placeholder && exampleText) {
+        const skipFiller =
+            (focused && placeholder && exampleText) ||
+            (textfield.size == 's' && !value.length) ||
```
Comment (waterplea) [inline projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts:61]: We should probably add linter on `==` instead of `===`

File: projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts (hunk 2 above)
Comment (splincode) [reply projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts:53]: unfortunately, one of the unit tests fails, do you think the problem is in the test?

File: projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts (hunk 3 above)
Comment (splincode) [reply projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts:61]: https://github.com/Tinkoff/taiga-ui/pull/1744

File: projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts (hunk 1 above)
Comment (splincode) [reply projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts]: fixed

File: projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts (hunk 2 above)
Comment (splincode) [reply projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts]: fixed

File: projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts (hunk 3 above)
Comment (splincode) [reply projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts]: fixed

File: projects/core/components/primitive-textfield/primitive-textfield.component.ts [hunk 4]
```diff
@@ -190,16 +190,29 @@ export class TuiPrimitiveTextfieldComponent
...
             this.nativeFocusableElement?.placeholder;
         const showDecor = hasDecor && !this.readOnly && this.computedFocused;
-        const placeholderVisible = !this.hasValue && !showDecor;
 
-        return this.placeholderRaisable || placeholderVisible;
+        return !this.hasValue && !showDecor;
+    }
+
+    get hasPlaceholder(): boolean {
+        return this.showOnlyPlaceholder
```
Comment (waterplea) [inline projects/core/components/primitive-textfield/primitive-textfield.component.ts:213]: `!this.showOnlyPlaceholder && (this.placeholderRaisable || this.placeholderVisible)`

**Review by waterplea — APPROVED** [review]

File: projects/core/components/primitive-textfield/primitive-textfield.component.ts (hunk 4 above)
Comment (splincode) [reply projects/core/components/primitive-textfield/primitive-textfield.component.ts]: fixed

**Review by vladimirpotekhin — APPROVED** [review]
