### PR TITLE
fix(addon-editor): improve ui/ux for font-size component

### LINKED ISSUE #2075: 🐞 - Font weight of title does not match with font weight of the dropdown
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/editor-new

### Is this issue blocking you?

Non-Blocking

### Description

If u select the title or subtitle in the editor, the font weight of the HTML does not match with the preview in the dropdown.

image

### Angular version

13.3.2

### Taiga UI version

2.52.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2075 

## What is the new behavior?

image

improved ui for display headers

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts [hunk 1]
```diff
@@ -18,24 +18,29 @@ import {map} from 'rxjs/operators';
...
+                            weight: 'bold',
+                        },
+                        {
+                            px: 30,
+                            family: 'var(--tui-font-heading)',
+                            name: texts.title,
+                            headingLevel: 1,
+                            weight: 'bold',
+                        },
+                    ] as TuiEditorFontOption[],
```
Comment (waterplea) [inline projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts:42]: Is this typecast necessary? 🤔

Comment (splincode) [reply projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts]: sorry, fixed

**Review by waterplea — APPROVED** [review]
