### PR TITLE
fix(addon-editor): trigger `updateValueAndValidity` after `focus/blur` events in `tui-editor`

### LINKED ISSUE #3938: 🐞 - Incorrect validation in Editor with image upload and loader
### Playground Link

https://stackblitz.com/edit/angular-pmxrfb?file=src/app/app.component.html

### Description

1. Add Editor with image upload and loader as in example https://taiga-ui.dev/editor/images/upload#upload-images
2. Add required validator for Editor.

Then when I upload image, I see validation error while it is uploading. When formControl receives value, the error disappears.

### Angular version

15.2.1

### Taiga UI version

3.21.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3938

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/addon-editor/directives/tiptap-editor/tiptap-editor.directive.ts [hunk 1]
```diff
@@ -42,6 +42,12 @@ export class TuiTiptapEditorDirective {
     @Output()
     readonly stateChange = this.editor.stateChange$;
 
+    @Output()
+    readonly focusChange = this.editor.focusChange$;
```
Comment (waterplea) [inline projects/addon-editor/directives/tiptap-editor/tiptap-editor.directive.ts:46]: Why do we need those? `focusin`/`focusout` events bubble. Also they are definitely not `change` if nothing changes :D We typically have `focusChange: Observable<boolean>` because it watches for focus and that state actually changes.

File: projects/demo/src/modules/components/editor/images/upload/examples/1/index.html [hunk 2]
```diff
@@ -1,11 +1,20 @@
-<tui-loader [showLoader]="!!(imgbbService.loading$ | async)">
+<tui-loader
+    [overlay]="true"
+    [showLoader]="!!(imgbbService.loading$ | async)"
+>
     <tui-editor
         class="editor"
         [formControl]="control"
         [tools]="builtInTools"
+        (blur)="control.updateValueAndValidity()"
```
Comment (waterplea) [inline projects/demo/src/modules/components/editor/images/upload/examples/1/index.html:9]: Why do we need to trigger it manually? Should `onTouched` from `ControlValueAccessor` take care of that? Also you seem to already be doing that inside component template by newly added focus/blur handlers.

File: projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts [hunk 3]
```diff
@@ -52,17 +55,29 @@ import {ImgbbService} from './imgbb.service';
...
+    ) {
         this.control.patchValue(
             '<img data-type="image-editor" src="/assets/images/lumberjack.png" width="300">' +
                 '<p>Try to drag right border of image!</p>' +
                 '<p>To change min/max size of image use token <code>TUI_IMAGE_EDITOR_OPTIONS</code>.</p>' +
                 '<img src="data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDUwIDUwIiB3aWR0aD0iNTAiIGhlaWdodD0iNTAiPjxzdHlsZT4uYXtmaWxsOiNkZDAwMzF9LmJ7ZmlsbDojYzMwMDJmfS5je2ZpbGw6I2ZmZn08L3N0eWxlPjxwYXRoIGNsYXNzPSJhIiBkPSJtNDMuNiAxMi42bC0yLjggMjQuNy0xNS44IDguNy0xNS44LTguNy0yLjgtMjQuNyAxOC42LTYuNnoiLz48cGF0aCBjbGFzcz0iYiIgZD0ibTI1IDZsMTguNiA2LjYtMi44IDI0LjctMTUuOCA4Ljd2LTE1LjMtMjAuMy00LjR6Ii8+PHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGFzcz0iYyIgZD0ibTM2LjYgMzYuNWgtNC4zbC0yLjQtNS44aC05LjlsLTIuMyA1LjhoLTQuM2wxMS42LTI2LjF6bS0xMS42LTE3LjZsLTMuNCA4LjJoNi44eiIvPjwvc3ZnPg==" />',
         );
     }
+
+    ngOnInit(): void {
```
Comment (waterplea) [inline projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts:78]: Maybe we can use `tuiValidator` directive for more declarative approach?

File: projects/demo/src/modules/components/editor/images/upload/examples/1/validator.ts [hunk 4]
```diff
@@ -0,0 +1,19 @@
...
+    service: ImgbbService,
+    editor: TuiEditorComponent,
+    documentRef: Document,
+): ValidatorFn {
+    return ({value}: AbstractControl) => {
+        const fileDialogIsOpen = !documentRef.hasFocus();
+
+        return editor.focused || service.isLoading || fileDialogIsOpen || value.length
+            ? null
+            : {maxLength: new TuiValidationError(`Error: content must not be empty`)};
```
Comment (waterplea) [inline projects/demo/src/modules/components/editor/images/upload/examples/1/validator.ts:17]: Why is it `maxLength`?

File: projects/addon-editor/components/editor/editor.component.ts [hunk 5]
```diff
@@ -135,6 +135,16 @@ export class TuiEditorComponent
         this.updateValue(value);
     }
 
+    onFocusChange(): void {
+        this.onActiveZone(true);
```
Comment (waterplea) [inline projects/addon-editor/components/editor/editor.component.ts:139]: Shouldn't `(tuiActiveZoneChange)` on `tuiWrapper` of editor component already take care of those focus/blur events?

File: projects/demo/src/modules/components/editor/images/upload/examples/1/index.html (hunk 2 above)
Comment (splincode) [reply projects/demo/src/modules/components/editor/images/upload/examples/1/index.html:9]: good catch, I forgot remove that line

File: projects/addon-editor/directives/tiptap-editor/tiptap-editor.directive.ts (hunk 1 above)
Comment (splincode) [reply projects/addon-editor/directives/tiptap-editor/tiptap-editor.directive.ts]: fixed

File: projects/demo/src/modules/components/editor/images/upload/examples/1/index.html (hunk 2 above)
Comment (splincode) [reply projects/demo/src/modules/components/editor/images/upload/examples/1/index.html]: fixed

File: projects/demo/src/modules/components/editor/images/upload/examples/1/validator.ts (hunk 4 above)
Comment (splincode) [reply projects/demo/src/modules/components/editor/images/upload/examples/1/validator.ts]: fixed

File: projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts (hunk 3 above)
Comment (splincode) [reply projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts]: fixed

File: projects/addon-editor/components/editor/editor.component.ts (hunk 5 above)
Comment (splincode) [reply projects/addon-editor/components/editor/editor.component.ts]: fixed

File: projects/addon-editor/components/editor/editor.component.html [hunk 6]
```diff
@@ -52,6 +52,8 @@
                 [editable]="interactive"
                 (valueChange)="onModelChange($event)"
                 (stateChange)="(0)"
+                (focusin)="control?.updateValueAndValidity()"
```
Comment (waterplea) [inline projects/addon-editor/components/editor/editor.component.html:55]: Can we move this into `onActiveZone` so that it is not triggered when we navigate around toolbar/dropdowns?

**Review by waterplea — APPROVED** [review]

File: projects/addon-editor/components/editor/editor.component.ts [hunk 7]
```diff
@@ -135,6 +135,11 @@ export class TuiEditorComponent
         this.updateValue(value);
     }
 
+    override updateFocused(focused: boolean): void {
+        this.focused = focused;
```
[the remark this answers is not in the document]
Comment (splincode) [reply projects/addon-editor/components/editor/editor.component.ts:139]: because onActiveZone didn’t call :( and I don’t know why

File: projects/addon-editor/components/editor/editor.component.html (hunk 6 above)
Comment (splincode) [reply projects/addon-editor/components/editor/editor.component.html:55]: I check it

File: projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts [hunk 8]
```diff
@@ -53,16 +55,32 @@ import {ImgbbService} from './imgbb.service';
...
                 '<p>Try to drag right border of image!</p>' +
                 '<p>To change min/max size of image use token <code>TUI_IMAGE_EDITOR_OPTIONS</code>.</p>' +
                 '<img src="data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDUwIDUwIiB3aWR0aD0iNTAiIGhlaWdodD0iNTAiPjxzdHlsZT4uYXtmaWxsOiNkZDAwMzF9LmJ7ZmlsbDojYzMwMDJmfS5je2ZpbGw6I2ZmZn08L3N0eWxlPjxwYXRoIGNsYXNzPSJhIiBkPSJtNDMuNiAxMi42bC0yLjggMjQuNy0xNS44IDguNy0xNS44LTguNy0yLjgtMjQuNyAxOC42LTYuNnoiLz48cGF0aCBjbGFzcz0iYiIgZD0ibTI1IDZsMTguNiA2LjYtMi44IDI0LjctMTUuOCA4Ljd2LTE1LjMtMjAuMy00LjR6Ii8+PHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGFzcz0iYyIgZD0ibTM2LjYgMzYuNWgtNC4zbC0yLjQtNS44aC05LjlsLTIuMyA1LjhoLTQuM2wxMS42LTI2LjF6bS0xMS42LTE3LjZsLTMuNCA4LjJoNi44eiIvPjwvc3ZnPg==" />',
         );
     }
+
+    readonly validator = ({value}: AbstractControl): ValidationErrors | null =>
+        this.editor.focused ||
+        this.imgbbService.isLoading ||
+        !this.documentRef.hasFocus() || // possible that file dialog is open
```
[the remark this answers is not in the document]
Comment (splincode) [reply projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts:80]: When file dialog is open we have error on background dialog (flaky)

[the remark this answers is not in the document]
Comment (waterplea) [reply projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts:80]: Ok, I guess it's better this way.

File: projects/addon-editor/components/editor/editor.component.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (splincode) [reply projects/addon-editor/components/editor/editor.component.ts]: fixed

File: projects/addon-editor/components/editor/editor.component.html (hunk 6 above)
Comment (splincode) [reply projects/addon-editor/components/editor/editor.component.html]: fixed

**Review by vladimirpotekhin — APPROVED** [review]
