### PR TITLE
fix(addon-charts): fix axis hints

### LINKED ISSUE #1195: 🐞 - LineDaysChart: Neither X-axis nor Y-axis stringifies functions don't work
### Which @taiga-ui/* package(s) are the source of the bug?

addon-charts

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/line-days-chart/API?tuiMode=null&xStringify$=0&yStringify$=0

### Description

Input parameters **xStringify** and **yStringify** don't affect axis hints appearance.

### Angular version

9.1.12

### Taiga UI version

2.29.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #1195 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/addon-charts/components/line-days-chart/line-days-chart.component.ts [hunk 1]
```diff
@@ -168,6 +168,8 @@ export class TuiLineDaysChartComponent {
 
         if (this.hintDirective) {
             this.hintDirective.raise(this.getMonth(x));
+        } else {
+            this.onHovered(this.getMonth(x));
```
Comment (splincode) [inline projects/addon-charts/components/line-days-chart/line-days-chart.component.ts:172]: what do you think about?)

```ts
const month = this.getMonth(x);

if (this.hintDirective) {
   this.hintDirective.raise(month);
 } else {
   this.onHovered(month);
}
```

Do we need to write e2e tests for this case?

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]
