### PR TITLE
fix(kit): `Stepper` use `TuiScrollService` instead of scrollIntoView

### LINKED ISSUE #3629: 🐞 - When current step is not the 1st Stepper doesn't scroll to active step
### Which @taiga-ui/* package(s) are the source of the bug?

testing

### Please provide a link to a minimal reproduction of the bug

_No response_

### Is this issue blocking you?

Non-Blocking

### Description

Prerequisite: 1. there is a page with steps which contains stepper on top of the page. Complete this page till in example 3 step  Screenshot 2023-02-06 at 20 02 59 
2. close this page 

Test case: 
Open page from prerequisite again

Expected results: 
page opens on last saved step 3 and stepper scrolls to this active step

Actual results: 
page opens on last saved step, but stepper shows the begging of steps which are not active. Stepper doesn't scroll to active step: 
Screenshot 2023-02-06 at 19 54 33

RU comment: степпер скролит шаги к текущему активному шагу, если передвигаться от 1го к последнему. Но если текуший активный шаг страницы не первый и страница ранее была закрыта (или например заполнялась на другом устройстве ранее), то при открытии степпер не покажет текущий активный шаг, а отмотает к первому. 

Additional info: 
this issue has been raised following by decision in https://github.com/Tinkoff/taiga-ui/issues/3616

### Angular version

15.0.4

### Taiga UI version

2.75.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [X] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3629

There is a chromium bug with `element.scrollIntoView` https://bugs.chromium.org/p/chromium/issues/detail?id=833617
Autoscroll doesn't work if there is more then one stepper on the page

## What is the new behavior?
With `TuiScrollService` scroll works correctly

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/kit/components/stepper/stepper.component.ts [hunk 1]
```diff
@@ -139,11 +142,26 @@ export class TuiStepperComponent {
...
+            offsetWidth,
+            offsetTop: stepOffsetTop,
+            offsetLeft: stepOffsetLeft,
+        } = step;
+        const top = stepOffsetTop - offsetTop - clientHeight / 2 + offsetHeight / 2;
+        const left = stepOffsetLeft - offsetLeft - clientWidth / 2 + offsetWidth / 2;
+
+        this.scrollService
+            .scroll$(nativeElement, Math.max(0, top), Math.max(0, left), 100)
+            .subscribe();
```
Comment (splincode) [inline projects/kit/components/stepper/stepper.component.ts:165]: takeUntil is needed here

File: projects/kit/components/stepper/stepper.component.ts [hunk 2]
```diff
@@ -99,6 +98,10 @@ export class TuiStepperComponent {
         this.moveFocus(event.target, step);
     }
 
+    ngAfterViewChecked(): void {
```
Comment (splincode) [inline projects/kit/components/stepper/stepper.component.ts:101]: How many times that method calls?

Comment (waterplea) [reply projects/kit/components/stepper/stepper.component.ts:101]: We need an early return if scrolling is unnecessary.

File: projects/kit/components/stepper/stepper.component.ts (hunk 1 above)
Comment (waterplea) [reply projects/kit/components/stepper/stepper.component.ts:165]: No, it completes in 100 ms anyway.

File: projects/kit/components/stepper/stepper.component.ts [hunk 3]
```diff
@@ -30,23 +33,14 @@ import {delay} from 'rxjs/operators';
...
-    block: 'center',
-    inline: 'nearest',
-};
-
 @Component({
     selector: 'tui-stepper, nav[tuiStepper]',
     templateUrl: './stepper.template.html',
     styleUrls: ['./stepper.style.less'],
     changeDetection: ChangeDetectionStrategy.OnPush,
+    providers: [TuiScrollService],
```
Comment (waterplea) [inline projects/kit/components/stepper/stepper.component.ts:41]: Unnecessary

File: projects/kit/components/stepper/stepper.component.ts [hunk 4]
```diff
@@ -56,19 +50,19 @@ export class TuiStepperComponent {
...
-    activeItemIndex = 0;
-
     constructor(
         @Inject(ChangeDetectorRef) private readonly changeDetector: ChangeDetectorRef,
-    ) {}
+        @Inject(ElementRef) private readonly elementRef: ElementRef<HTMLElement>,
+        @Inject(TuiScrollService) private readonly scrollService: TuiScrollService,
+        @Inject(TuiResizeService) resize$: Observable<void>,
+    ) {
+        resize$.subscribe(() => this.changeDetector.markForCheck());
```
Comment (waterplea) [inline projects/kit/components/stepper/stepper.component.ts:64]: Why do we need it? It's a heavy performance hit.

Comment (vladimirpotekhin) [reply projects/kit/components/stepper/stepper.component.ts]: finally remade without hooks, this way seems like performance is ok
take a look plz

File: projects/kit/components/stepper/stepper.component.ts [hunk 5]
```diff
@@ -68,7 +62,12 @@ export class TuiStepperComponent {
 
     constructor(
         @Inject(ChangeDetectorRef) private readonly changeDetectorRef: ChangeDetectorRef,
-    ) {}
+        @Inject(ElementRef) private readonly elementRef: ElementRef<HTMLElement>,
+        @Inject(TuiScrollService) private readonly scrollService: TuiScrollService,
+        @Inject(TuiResizeService) resize$: Observable<void>,
+    ) {
+        resize$.subscribe(() => this.scrollIntoView(this.activeItemIndex));
```
Comment (splincode) [inline projects/kit/components/stepper/stepper.component.ts:69]: I'm not sure, but for safety takeUntil is needed?

Comment (vladimirpotekhin) [reply projects/kit/components/stepper/stepper.component.ts:69]: there is takeUntil inside resizeService

**Review by waterplea — APPROVED** [review]
