### PR TITLE
fix(kit): clamp activeIndex for `tabs-with-more`

### LINKED ISSUE #2090: 🐞 - Выбрана фантомная активная таба в TuiTabsWithMoreComponent
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-nsr1qu?file=src/app/app.component.html

### Is this issue blocking you?

Non-Blocking

### Description

При передаче значение в activeItemIndex на 1 больше, чем кол-во табов, селектится фантомная таба.
Снимок экрана 2022-07-11 в 11 54 06

### Angular version

11.2.13

### Taiga UI version

2.52.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2090 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts [hunk 1]
```diff
@@ -129,6 +144,16 @@ export class TuiTabsWithMoreComponent implements AfterViewInit {
         return Math.min(this.itemsLimit - offset, this.maxIndex);
     }
 
+    @tuiPure
+    isOverflown(index: number): boolean {
+        return index !== this.activeItemIndex || !this.options.exposeActive;
+    }
+
+    @tuiPure
```
Comment (vladimirpotekhin) [inline projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts:152]: tuiPure is useless (methods are called from ngFor in template)

Comment (splincode) [reply projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts]: fixed
