### PR TITLE
fix(core): escape event doesn't work in Safari

### LINKED ISSUE #3741: 🐞 - Escape event doesn't work in Safari for TuiHostedDropdown
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-sjpzht-t2uafm?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts&hideExplorer=1

### Is this issue blocking you?

Blocking

### Description

Open an interface with tui-hosted-dropdown component in Safari and try close it with press on Esc key.

**Expected result:**
Add posibillity to close dropdown with press on Esc key in Safari.

### Angular version

14.2.7

### Taiga UI version

3.2

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3741

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/eslint-plugin/rules/accessibility.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+                    for (const argument of args) {
+                        const invalidEscape =
+                            argument.value === `keydown.esc` ||
+                            argument.value === `document:keydown.esc`;
+
+                        if (invalidEscape) {
+                            context.report({
+                                node,
+                                message: `Don't use "*:keydown.esc" instead of "*:keydown.escape"`,
```
[the remark this answers is not in the document]
Comment (splincode) [reply projects/eslint-plugin/rules/accessibility.js]: fixed

[the remark this answers is not in the document]
Comment (waterplea) [reply projects/eslint-plugin/rules/accessibility.js]: Safari is true IE of our times. Only IE has it called `escape` :)

File: projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts [hunk 2]
```diff
@@ -303,7 +303,7 @@ export class TuiInputCardGroupedComponent
         return this.cardPrefilled ? `*${this.card.slice(-4)}` : '*';
     }
 
-    @HostListener('keydown.esc')
+    @HostListener('document:keydown.escape')
```
Comment (waterplea) [inline projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts:306]: This would cause change detection on every escape keypress on the document. While this component is rarely used, I'd still like to avoid that.

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 3]
```diff
@@ -159,7 +159,7 @@ export class TuiHostedDropdownComponent implements TuiFocusableElementAccessor {
         }
     }
 
-    @HostListener('keydown.esc', ['$event'])
+    @HostListener('document:keydown.escape', ['$event'])
```
Comment (waterplea) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:162]: This would cause change detection on every escape keypress on the document. This is a very common component, we definitely want to avoid that.

**Review by waterplea — CHANGES_REQUESTED** [review]

File: projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts (hunk 2 above)
Comment (splincode) [reply projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts]: fixed

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 3 above)
Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts]: fixed

File: projects/eslint-plugin/configs/all.json [hunk 4]
```diff
@@ -4,6 +4,7 @@
         "@taiga-ui/injection-token-description": "error",
         "@taiga-ui/prefer-inject-decorator": "error",
         "@taiga-ui/prefer-self-destroy-service": "error",
+        "@taiga-ui/accessibility": "error",
```
Comment (splincode) [inline projects/eslint-plugin/configs/all.json:7]: @nsbarsukov @vladimirpotekhin what do you think about name?

Comment (nsbarsukov) [reply projects/eslint-plugin/configs/all.json:7]: Maybe it is better to call it directly `@taiga-ui/no-esc-keydown` ?

**Review by nsbarsukov — APPROVED** [review]

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 3 above)
Comment (waterplea) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:162]: Maybe we can use `.silent` and `@shouldCall`? But they don't work with angular keydown effects, so we would need to filter for `escape` button inside `@shouldCall` predicate.

File: projects/eslint-plugin/configs/all.json (hunk 4 above)
Comment (splincode) [reply projects/eslint-plugin/configs/all.json]: fixed

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 3 above)
Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts]: `.silent` works as well

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 3 above)
Comment (waterplea) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts]: It will not work, because Angular re-enters the zone in those keydown events, so it works, but it's not «silent».

Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts]: @waterplea you are right, sorry for that

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 5]
```diff
@@ -42,6 +43,10 @@ export interface TuiHostedDropdownContext
     close(): void;
 }
 
+function activeZoneFilter(this: TuiHostedDropdownComponent): boolean {
+    return this.isLastOpenedDropdown && this.activeZone.contains(this.wrapperElement);
```
Comment (waterplea) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:47]: This is not what we need to be testing here. We need to test if the key pressed is escape and that the dropdown is open (`this.open`).

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 6]
```diff
@@ -159,7 +172,8 @@ export class TuiHostedDropdownComponent implements TuiFocusableElementAccessor {
         }
     }
 
-    @HostListener('keydown.esc', ['$event'])
+    @shouldCall(activeZoneFilter)
+    @HostListener('document:keydown.escape', ['$event'])
```
Comment (waterplea) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:176]: Right now there's no point in this code. `@shouldCall` is used for filtering calls and **re-entering** the zone. We did not leave the zone, so all we did is write a very complex early return. We need `@HostListener('document:keydown.silent')` and inside `@shouldCall` we need to filter for escape key, because Angular re-enters zone if we rely on its built-in event manager plugin (`keydown.escape`). This can also be reused in `InputCardGrouped`.

**Review by waterplea — CHANGES_REQUESTED** [review]

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 5 above)
Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:47]: image

And so, we have 2 open dropdown box. Expected behavior after the escape only the last one will be closed and so that it is:

image

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 6 above)
Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:176]: `Right now there's no point in this code. ` it would be great if there would be a eslint rule for that

Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts]: fixed

**Comment by splincode** [comment]
@waterplea @nsbarsukov @vladimirpotekhin hello, please could you review me?

**Comment by splincode** [comment]
@waterplea updated

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 7]
```diff
@@ -42,6 +43,17 @@ export interface TuiHostedDropdownContext
     close(): void;
 }
 
+function shouldEscape(this: TuiHostedDropdownComponent, event: KeyboardEvent): boolean {
+    const wrapperElement = this.wrapperElement;
+
+    return (
+        event.key.toLowerCase() === 'escape' &&
+        this.isLastOpenedDropdown &&
+        !!wrapperElement &&
```
Comment (waterplea) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:52]: What's the point of `wrapperElement` and especially checking if it's inside the zone? It **cannot** be outside the zone if it exists. Besides there's an early return for `!this.open` in `onKeyDownEsc` which already handles the case of ignoring escape when dropdown is closed (this early return should probably be moved in `shouldEscape` so that early return is handled in one place).

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 8]
```diff
@@ -106,6 +118,14 @@ export class TuiHostedDropdownComponent implements TuiFocusableElementAccessor {
         return this.openChange.value;
     }
 
+    get isLastOpenedDropdown(): boolean {
+        return !!this.dropdown && !this.dropdown?.nextElementSibling;
```
Comment (waterplea) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:122]: Unnecessary test for `!!this.dropdown` if we will test for `this.open` anyway. `dropdown` is already public, let's just move this test for `nextElementSibling` inside `shouldEscape`. `shouldClose` is also probably a better name for that predicate :)

**Review by waterplea — CHANGES_REQUESTED** [review]

File: projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts [hunk 9]
```diff
@@ -303,7 +315,8 @@ export class TuiInputCardGroupedComponent
         return this.cardPrefilled ? `*${this.card.slice(-4)}` : '*';
     }
 
-    @HostListener('keydown.esc')
+    @shouldCall(shouldEscape)
+    @HostListener('document:keydown.silent', ['$event'])
```
[the remark this answers is not in the document]
Comment (splincode) [reply projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts]: fixed

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 7 above)
Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts]: fixed

**Review by waterplea — APPROVED** [review]
