### PR TITLE
fix(addon-table): type string is not assignable to type keyof T

### LINKED ISSUE #2585: 🐞 - Tables - tuiHead type error
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Is this issue blocking you?

Non-Blocking

### Description

`<th *tuiHead="'name'" tuiTh>Name</th>`

Typescript error:
Error:(11, 21) Type "name" is not assignable to type keyof T

### Angular version

14.0.0

### Taiga UI version

3.0.1

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2585

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by vladimirpotekhin — APPROVED** [review]

File: projects/cdk/types/typed-of.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+/**
+ * @note:
+ * Basically problem:
+ * Typescript type string is not assignable to type keyof
+ *
+ * The reason you get an error is that typescript will not infer string literal types for const members or unknown(T).
+ * You can force the compiler to infer string literal types by using an extra utility
+ */
+export type TuiTypedOf<T, K = any> = {
```
Comment (nsbarsukov) [inline projects/cdk/types/typed-of.ts:9]:
```suggestion
export type TuiTypedRecord<T, K = any> = {
```
?

Comment (splincode) [reply projects/cdk/types/typed-of.ts]: fixed
