### PR TITLE
fix(core): `DropdownHover` properly reflect state for `HostedDropdown`

### LINKED ISSUE #3372: 🐞 - `TuiHostedDropdown` doesn't reflect open state when `tuiDropdownHover` is used
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-argxkc?file=src%2Fapp%2Fapp.component.html

### Is this issue blocking you?

Non-Blocking

### Description

The open state of the `TuiHostedDropdown` is always its initial value.

### Angular version

15.0.0

### Taiga UI version

3.15.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by waterplea**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3372

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts [hunk 1]
```diff
@@ -59,7 +60,8 @@ export class TuiHostedDropdownComponent implements TuiFocusableElementAccessor {
     @ViewChild(TuiDropdownDirective)
     private readonly dropdownDirective?: TuiDropdownDirective;
 
-    private readonly manual$ = new BehaviorSubject(false);
+    /** TODO: rename in 4.0 */
+    readonly openChange = new BehaviorSubject(false);
```
Comment (splincode) [inline projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:64]: you can use `private` and skip `eslint-disable @typescript-eslint/member-ordering`

**Review by splincode — APPROVED** [review]

File: projects/core/components/hosted-dropdown/hosted-dropdown.component.ts (hunk 1 above)
Comment (waterplea) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:64]: Some things, like TUI_ARROW rely on `openChange` being public `EventEmitter`,

Comment (splincode) [reply projects/core/components/hosted-dropdown/hosted-dropdown.component.ts:64]: sorry

**Review by nsbarsukov — APPROVED** [review]
