### PR TITLE
fix(addon-editor): edit link modal shouldn't overlap content

### LINKED ISSUE #2721: 🐞 - [addon-editor] Link editing doesn't work properly
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/editor/API?tuiMode=null&ngModel=%3Cp%3E%3Ca%20target%3D%22_blank%22%20rel%3D%22noopener%20noreferrer%20nofollow%22%20href%3D%22http:%2F%2Fgoogle.com%22%3Elink%3C%2Fa%3E%3C%2Fp%3E

### Is this issue blocking you?

Blocking

### Description

Link editing doesn't work properly:

I can edit, but after clicking 'v' button, popup window for editing remains opened, while link url sometimes(!) changes and sometimes remains the same

### Angular version

12.2.16

### Taiga UI version

2.62.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by splincode**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2721

https://user-images.githubusercontent.com/12021443/193824358-0bf1539e-ec88-427f-8a12-931eacb484b6.mov

## What is the new behavior?

https://user-images.githubusercontent.com/12021443/193824586-8f17388e-cced-4f39-a1ed-7e20eba12695.mov

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by waterplea — APPROVED** [review]

File: projects/addon-editor/components/editor/editor.component.ts [hunk 1]
```diff
@@ -133,8 +136,19 @@ export class TuiEditorComponent
         return ``;
     }
 
-    private readonly isSelectionLink = ({startContainer, endContainer}: Range): boolean =>
-        !!startContainer.parentElement?.closest(`a`)?.contains(endContainer);
+    private readonly isSelectionLink = (range: Range): boolean =>
+        this.currentFocusedNodeIsAnchor(range) && this.isSafeRangeForTextNode(range);
+
+    private currentFocusedNodeIsAnchor(range: Range): boolean {
+        return !!range.startContainer.parentElement
```
Comment (waterplea) [inline projects/addon-editor/components/editor/editor.component.ts:143]: Can this just be `!!range.commonAncestorContainer.closest('a')`?

Comment (splincode) [reply projects/addon-editor/components/editor/editor.component.ts:143]: I tried to use this but for some reason the range object returns the previous text element in commonAncestorContainer. Though at the same time, when the cursor is on another line, there should have been a new element.

File: projects/addon-editor/components/editor/editor.component.ts [hunk 2]
```diff
@@ -133,8 +136,19 @@ export class TuiEditorComponent
...
+            ?.closest(`a`)
+            ?.contains(this.documentRef.getSelection()?.focusNode || null);
+    }
+
+    private readonly isSafeRangeForTextNode = (range: Range): boolean =>
```
[the remark this answers is not in the document]
Comment (splincode) [reply projects/addon-editor/components/editor/editor.component.ts]: fixed

**Review by vladimirpotekhin — APPROVED** [review]
