### PR TITLE
fix(kit): `InputDateTime` fix value setting when using valueTransformer

### LINKED ISSUE #3155: 🐞 -TuiInputDateTimeComponent  value is not always displayed after transformation with TuiControlValueTransformer
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-n7dmly?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fto-native-date-time.directive.ts&hideExplorer=1

### Is this issue blocking you?

Non-Blocking

### Description

I'm trying to use directive to transform value at TuiInputDateTimeComponent like in this example https://taiga-ui.dev/components/input-date-time#string-control-output

When I try to update this value, it is not displayed in control

### Angular version

13.3.4

### Taiga UI version

2.62.3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by vladimirpotekhin**
## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3155

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by splincode — APPROVED** [review]

File: projects/kit/components/input-date-time/input-date-time.component.ts [hunk 1]
```diff
@@ -312,7 +312,7 @@ export class TuiInputDateTimeComponent
 
     override writeValue(value: [TuiDay | null, TuiTime | null] | null): void {
         super.writeValue(value);
-
+        value = this.value;
```
Comment (waterplea) [inline projects/kit/components/input-date-time/input-date-time.component.ts:315]: I think using `this.value` below makes more sense than resigning `value`

**Review by waterplea — APPROVED** [review]
