### PR TITLE
fix(kit): `TabsWithMore` properly calculate overflow

### LINKED ISSUE #3682: 🐞 - Некорректное отображение табов третьего уровня Navigation, если текст заголовка очень длинный
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

-

### Is this issue blocking you?

Blocking

### Description

Если заголовок в третьем уровне меню имеет длинный текст, то заголовок наезжает на табы, табы не сворачиваются в многоточие, часть табов не отображается

можно наиграть [на витрине](https://angular-kit-qa.tcsbank.ru/navigation/navigation#three), сделав текст заголовка длинным

image

### Angular version

12.x.x

### Taiga UI version

2.76.0, 3.17.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by waterplea**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [ ] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #3682

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts [hunk 1]
```diff
@@ -216,7 +216,7 @@ export class TuiTabsWithMoreComponent implements AfterViewInit {
         let total =
             tabs.reduce((acc, {scrollWidth}) => acc + scrollWidth, 0) +
             maxIndex * margin -
-            moreWidth;
+            tabs[tabs.length - 1].scrollWidth;
```
Comment (splincode) [inline projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts:219]: is it possible NPE?

**Review by splincode — APPROVED** [review]

File: projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts (hunk 1 above)
Comment (waterplea) [reply projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts:219]: No, this is "more" tab, it is always there.

**Review by nsbarsukov — APPROVED** [review]
